# Generated by Django 3.2.24 on 2024-02-21 00:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trees', '0004_profile_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlantedTree',
            new_name='Plant',
        ),
    ]
