# Generated by Django 3.2.24 on 2024-02-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0006_auto_20240221_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='planted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
